import type {
  AdminProperty,
  AdminPropertiesStats,
  AgencyRanking,
  AppSettings,
  InternalUser,
  ReportsStats,
  RevenueMonth,
  VisitRequest,
  VisitRequestsStats,
} from "@/lib/types";

// ----- Propiedades (admin catalog) -----

export const mockAdminPropertiesStats: AdminPropertiesStats = {
  total: 239,
  rent: 152,
  sale: 87,
  featured: 18,
};

export const mockAdminProperties: AdminProperty[] = [
  {
    id: "ap-1",
    reference: "BM-9876",
    title: "Ático en Recoletos",
    zone: "Recoletos",
    agencyId: "barnes",
    agencyName: "Barnes Madrid",
    operation: "alquiler",
    status: "available",
    bedrooms: 3,
    bathrooms: 3,
    squareMeters: 142,
    price: 6500,
    publishedLabel: "12/05/2026",
    featured: true,
  },
  {
    id: "ap-2",
    reference: "LF-2210",
    title: "Casa en La Moraleja",
    zone: "Chamartín",
    agencyId: "lucas-fox",
    agencyName: "Lucas Fox Madrid",
    operation: "venta",
    status: "available",
    bedrooms: 5,
    bathrooms: 4,
    squareMeters: 480,
    price: 4200000,
    publishedLabel: "11/05/2026",
    featured: true,
  },
  {
    id: "ap-3",
    reference: "AC-1820",
    title: "Piso reformado en Chamberí",
    zone: "Chamberí",
    agencyId: "alvora",
    agencyName: "Álvora Capital Properties",
    operation: "alquiler",
    status: "reserved",
    bedrooms: 2,
    bathrooms: 2,
    squareMeters: 95,
    price: 2900,
    publishedLabel: "09/05/2026",
  },
  {
    id: "ap-4",
    reference: "DC-0744",
    title: "Dúplex en Justicia",
    zone: "Justicia",
    agencyId: "de-salas",
    agencyName: "De Salas Luxury Homes",
    operation: "venta",
    status: "available",
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 130,
    price: 1295000,
    publishedLabel: "08/05/2026",
  },
  {
    id: "ap-5",
    reference: "CP-3301",
    title: "Estudio en Malasaña",
    zone: "Malasaña",
    agencyId: "consulting",
    agencyName: "Consulting Properties",
    operation: "alquiler",
    status: "rented",
    bedrooms: 1,
    bathrooms: 1,
    squareMeters: 55,
    price: 1450,
    publishedLabel: "06/05/2026",
  },
  {
    id: "ap-6",
    reference: "WH-0912",
    title: "Bajo con jardín en Retiro",
    zone: "Retiro",
    agencyId: "walter-haus",
    agencyName: "Walter Haus",
    operation: "alquiler",
    status: "available",
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 165,
    price: 4800,
    publishedLabel: "05/05/2026",
  },
  {
    id: "ap-7",
    reference: "NB-5512",
    title: "Piso en Salamanca",
    zone: "Salamanca",
    agencyId: "nappo",
    agencyName: "Nappo Real Estate",
    operation: "venta",
    status: "sold",
    bedrooms: 4,
    bathrooms: 3,
    squareMeters: 180,
    price: 2100000,
    publishedLabel: "30/04/2026",
  },
  {
    id: "ap-8",
    reference: "BM-9421",
    title: "Bajo con jardín en Chamartín",
    zone: "Chamartín",
    agencyId: "barnes",
    agencyName: "Barnes Madrid",
    operation: "alquiler",
    status: "draft",
    bedrooms: 2,
    bathrooms: 2,
    squareMeters: 110,
    price: 2900,
    publishedLabel: "—",
  },
];

// ----- Solicitudes (visit requests) -----

export const mockVisitRequestsStats: VisitRequestsStats = {
  total: 126,
  pending: 18,
  confirmed: 84,
  thisWeek: 23,
};

export const mockVisitRequests: VisitRequest[] = [
  {
    id: "vr-1",
    clientName: "María Rodríguez",
    clientInitials: "MR",
    propertyTitle: "Piso en Salamanca",
    propertyReference: "BM-9876",
    requestedDateLabel: "24 May 2026, 11:00",
    channelKey: "solicitudes.channel.portal",
    assignedAdvisor: "Laura Gómez",
    status: "confirmed",
    receivedRelativeMinutes: 12,
  },
  {
    id: "vr-2",
    clientName: "Javier Blanco",
    clientInitials: "JB",
    propertyTitle: "Ático en Recoletos",
    propertyReference: "BM-9421",
    requestedDateLabel: "25 May 2026, 17:30",
    channelKey: "solicitudes.channel.whatsapp",
    assignedAdvisor: "Carlos Ruiz",
    status: "pending",
    receivedRelativeMinutes: 45,
  },
  {
    id: "vr-3",
    clientName: "Clara Pérez",
    clientInitials: "CP",
    propertyTitle: "Estudio en Malasaña",
    propertyReference: "CP-3301",
    requestedDateLabel: "27 May 2026, 10:00",
    channelKey: "solicitudes.channel.portal",
    assignedAdvisor: "Laura Gómez",
    status: "rescheduled",
    receivedRelativeMinutes: 95,
  },
  {
    id: "vr-4",
    clientName: "Tech Solutions S.L.",
    clientInitials: "TS",
    propertyTitle: "Casa en La Moraleja",
    propertyReference: "LF-2210",
    requestedDateLabel: "28 May 2026, 12:30",
    channelKey: "solicitudes.channel.phone",
    assignedAdvisor: "Marta López",
    status: "confirmed",
    receivedRelativeMinutes: 180,
  },
  {
    id: "vr-5",
    clientName: "Ana Vázquez",
    clientInitials: "AV",
    propertyTitle: "Piso en Salamanca",
    propertyReference: "NB-5512",
    requestedDateLabel: "20 May 2026, 16:00",
    channelKey: "solicitudes.channel.portal",
    assignedAdvisor: "Laura Gómez",
    status: "completed",
    receivedRelativeMinutes: 720,
  },
  {
    id: "vr-6",
    clientName: "Luis Martínez",
    clientInitials: "LM",
    propertyTitle: "Bajo con jardín en Retiro",
    propertyReference: "WH-0912",
    requestedDateLabel: "26 May 2026, 18:00",
    channelKey: "solicitudes.channel.portal",
    assignedAdvisor: "Marta López",
    status: "rejected",
    receivedRelativeMinutes: 240,
  },
];

// ----- Reportes -----

export const mockReportsStats: ReportsStats = {
  monthlyCommissionsEUR: 184500,
  monthlyClosedDeals: 17,
  conversionRatePct: 23,
  averageDaysToClose: 42,
};

export const mockRevenueByMonth: RevenueMonth[] = [
  { monthKey: "month.short.dec", rentEUR: 38200, saleEUR: 92000 },
  { monthKey: "month.short.jan", rentEUR: 41500, saleEUR: 110000 },
  { monthKey: "month.short.feb", rentEUR: 39800, saleEUR: 98500 },
  { monthKey: "month.short.mar", rentEUR: 47100, saleEUR: 145200 },
  { monthKey: "month.short.apr", rentEUR: 51400, saleEUR: 128900 },
  { monthKey: "month.short.may", rentEUR: 54300, saleEUR: 130200 },
];

export const mockAgencyRanking: AgencyRanking[] = [
  {
    agencyId: "lucas-fox",
    name: "Lucas Fox Madrid",
    initials: "LF",
    closedDeals: 12,
    commissionsEUR: 78500,
  },
  {
    agencyId: "barnes",
    name: "Barnes Madrid",
    initials: "BR",
    closedDeals: 9,
    commissionsEUR: 64200,
  },
  {
    agencyId: "alvora",
    name: "Álvora Capital Properties",
    initials: "AC",
    closedDeals: 7,
    commissionsEUR: 41800,
  },
  {
    agencyId: "nappo",
    name: "Nappo Real Estate",
    initials: "NB",
    closedDeals: 5,
    commissionsEUR: 32900,
  },
  {
    agencyId: "de-salas",
    name: "De Salas Luxury Homes",
    initials: "DC",
    closedDeals: 4,
    commissionsEUR: 28100,
  },
];

// ----- Usuarios internos -----

export const mockInternalUsers: InternalUser[] = [
  {
    id: "u-bcousino",
    firstName: "Benjamín",
    lastName: "Cousiño",
    email: "benjamin@bencousinopropiedades.com",
    initials: "BC",
    roleKey: "owner",
    status: "active",
    lastLoginText: "Hoy, 09:12",
    joinedLabel: "Ene 2024",
  },
  {
    id: "u-laura",
    firstName: "Laura",
    lastName: "Gómez",
    email: "laura@bencousinopropiedades.com",
    initials: "LG",
    roleKey: "admin",
    status: "active",
    lastLoginText: "Hoy, 10:42",
    joinedLabel: "Mar 2024",
  },
  {
    id: "u-carlos",
    firstName: "Carlos",
    lastName: "Ruiz",
    email: "carlos@bencousinopropiedades.com",
    initials: "CR",
    roleKey: "advisor",
    status: "active",
    lastLoginText: "Ayer, 18:20",
    joinedLabel: "Abr 2024",
  },
  {
    id: "u-marta",
    firstName: "Marta",
    lastName: "López",
    email: "marta@bencousinopropiedades.com",
    initials: "ML",
    roleKey: "advisor",
    status: "active",
    lastLoginText: "Hoy, 11:05",
    joinedLabel: "Sep 2024",
  },
  {
    id: "u-javier",
    firstName: "Javier",
    lastName: "Cousiño",
    email: "javier@bencousinopropiedades.com",
    initials: "JC",
    roleKey: "admin",
    status: "active",
    lastLoginText: "Hoy, 08:30",
    joinedLabel: "Ene 2024",
  },
  {
    id: "u-pending",
    firstName: "Sara",
    lastName: "Mendez",
    email: "sara@bencousinopropiedades.com",
    initials: "SM",
    roleKey: "viewer",
    status: "invited",
    joinedLabel: "—",
  },
];

// ----- Settings -----

export const mockAppSettings: AppSettings = {
  company: {
    name: "Benjamín Cousiño Propiedades",
    legalName: "Benjamín Cousiño Propiedades S.L.",
    taxId: "B-12345678",
    address: "Calle de Velázquez, 76, 28001 Madrid",
    phone: "+34 91 123 45 67",
    email: "info@bencousinopropiedades.com",
  },
  branding: {
    primaryColor: "#0a0a0a",
    accentColor: "#c9a96e",
  },
  defaults: {
    language: "es",
    rentCommissionPct: 35,
    saleCommissionPct: 25,
    personalShopperMonths: 1,
  },
  notifications: {
    visitRequests: true,
    newClients: true,
    weeklyReport: true,
    propertyUpdates: false,
  },
};
