import { mockAgencies } from "@/lib/mock-agencies";
import type { Agency, AgencyDetail, AgencyPropertyRow } from "@/lib/types";

const DEFAULT_CONDITIONS = [
  "sharedCapture",
  "coordinatedVisits",
  "operationCommission",
  "verifiedDocumentation",
] as const;

// One detailed entry per agency. Only Barnes is fully fleshed out for the
// design; the rest reuse defaults so every agency has a working detail page.
export const mockAgencyDetails: Record<string, AgencyDetail> = {
  level: extend(mockAgencies[0], {
    status: "active",
    country: "España",
    partnerSinceLabel: "Ene 2022",
    // Level cobra el 50% de nuestra comisión en alquiler (todo desde 3.000 €/mes)
    // y el 50% de la comisión acordada en venta (acordada por defecto 4% → 2%).
    rentCommissionPct: 50,
    saleCommissionPct: 2,
    rentCommissionMinPrice: 3000,
    saleCommissionMinPrice: 0,
    saleAgreedCommissionPct: 4,
    conditionKeys: [...DEFAULT_CONDITIONS],
    contact: {
      name: "Carmen Braojos",
      initials: "CB",
      roleKey: "agency.contact.role.alliancesDirector",
      phone: "+34 619 66 65 67",
      email: "carmen@levelrealestate.es",
      address: "Madrid, España",
    },
    properties: [
      {
        id: "level-9876",
        title: "Ático en Recoletos",
        reference: "LV-9876",
        operation: "alquiler",
        zone: "Recoletos",
        bedrooms: 3,
        bathrooms: 3,
        price: 6500,
        squareMeters: 180,
        status: "available",
        lastUpdateMinutes: 10,
      },
      {
        id: "level-9574",
        title: "Piso en Salamanca",
        reference: "LV-9574",
        operation: "venta",
        zone: "Salamanca",
        bedrooms: 4,
        bathrooms: 3,
        price: 1850000,
        squareMeters: 220,
        status: "available",
        lastUpdateMinutes: 25,
      },
      {
        id: "level-9421",
        title: "Bajo con jardín en Chamartín",
        reference: "LV-9421",
        operation: "alquiler",
        zone: "Chamartín",
        bedrooms: 2,
        bathrooms: 2,
        price: 2900,
        squareMeters: 125,
        status: "reserved",
        lastUpdateMinutes: 60,
      },
      {
        id: "level-9333",
        title: "Dúplex en Justicia",
        reference: "LV-9333",
        operation: "venta",
        zone: "Justicia",
        bedrooms: 3,
        bathrooms: 2,
        price: 1295000,
        squareMeters: 165,
        status: "available",
        lastUpdateMinutes: 120,
      },
    ],
  }),
  alvora: extend(mockAgencies[1], {
    status: "active",
    country: "España",
    partnerSinceLabel: "Mar 2023",
    rentCommissionPct: 30,
    saleCommissionPct: 22,
    rentCommissionMinPrice: 1800,
    saleCommissionMinPrice: 450000,
    saleAgreedCommissionPct: 4,
    conditionKeys: [...DEFAULT_CONDITIONS],
    contact: {
      name: "Carlos López",
      initials: "CL",
      roleKey: "agency.contact.role.alliancesDirector",
      phone: "+34 91 555 12 34",
      email: "clopez@alvora.com",
      address: "Paseo de la Castellana, 120, 28046 Madrid, España",
    },
    properties: makeFallbackProperties("AL"),
  }),
  "de-salas": extend(mockAgencies[2], {
    status: "active",
    country: "España",
    partnerSinceLabel: "Sep 2022",
    rentCommissionPct: 32,
    saleCommissionPct: 24,
    rentCommissionMinPrice: 2000,
    saleCommissionMinPrice: 500000,
    saleAgreedCommissionPct: 4,
    conditionKeys: [...DEFAULT_CONDITIONS],
    contact: {
      name: "Lucía Fernández",
      initials: "LF",
      roleKey: "agency.contact.role.alliancesDirector",
      phone: "+34 91 444 55 66",
      email: "lucia@desalas.es",
      address: "Calle de Velázquez, 22, 28001 Madrid, España",
    },
    properties: makeFallbackProperties("DS"),
  }),
  "lucas-fox": extend(mockAgencies[3], {
    status: "active",
    country: "España",
    partnerSinceLabel: "Jun 2021",
    rentCommissionPct: 38,
    saleCommissionPct: 28,
    rentCommissionMinPrice: 3000,
    saleCommissionMinPrice: 750000,
    saleAgreedCommissionPct: 5,
    conditionKeys: [...DEFAULT_CONDITIONS],
    contact: {
      name: "Pablo Hernández",
      initials: "PH",
      roleKey: "agency.contact.role.alliancesDirector",
      phone: "+34 91 700 80 90",
      email: "p.hernandez@lucasfox.es",
      address: "Calle de Goya, 47, 28001 Madrid, España",
    },
    properties: makeFallbackProperties("LF"),
  }),
  consulting: extend(mockAgencies[4], {
    status: "active",
    country: "España",
    partnerSinceLabel: "Feb 2024",
    rentCommissionPct: 28,
    saleCommissionPct: 20,
    rentCommissionMinPrice: 1500,
    saleCommissionMinPrice: 350000,
    saleAgreedCommissionPct: 4,
    conditionKeys: [...DEFAULT_CONDITIONS],
    contact: {
      name: "Sofía Martín",
      initials: "SM",
      roleKey: "agency.contact.role.alliancesDirector",
      phone: "+34 91 230 11 22",
      email: "sofia@consultingproperties.com",
      address: "Calle de Alcalá, 200, 28028 Madrid, España",
    },
    properties: makeFallbackProperties("CP"),
  }),
  "walter-haus": extend(mockAgencies[5], {
    status: "active",
    country: "España",
    partnerSinceLabel: "Oct 2023",
    rentCommissionPct: 27,
    saleCommissionPct: 21,
    rentCommissionMinPrice: 1400,
    saleCommissionMinPrice: 320000,
    saleAgreedCommissionPct: 4,
    conditionKeys: [...DEFAULT_CONDITIONS],
    contact: {
      name: "Helena García",
      initials: "HG",
      roleKey: "agency.contact.role.alliancesDirector",
      phone: "+34 91 345 67 89",
      email: "hgarcia@walterhaus.com",
      address: "Calle de Padilla, 14, 28006 Madrid, España",
    },
    properties: makeFallbackProperties("WH"),
  }),
  nappo: extend(mockAgencies[6], {
    status: "active",
    country: "España",
    partnerSinceLabel: "Jul 2023",
    rentCommissionPct: 33,
    saleCommissionPct: 23,
    rentCommissionMinPrice: 2200,
    saleCommissionMinPrice: 480000,
    saleAgreedCommissionPct: 4,
    conditionKeys: [...DEFAULT_CONDITIONS],
    contact: {
      name: "Andrea Bueno",
      initials: "AB",
      roleKey: "agency.contact.role.alliancesDirector",
      phone: "+34 91 678 90 12",
      email: "abueno@napporealestate.com",
      address: "Plaza de la Lealtad, 4, 28014 Madrid, España",
    },
    properties: makeFallbackProperties("NB"),
  }),
  gilmar: extend(mockAgencies[7], {
    status: "inactive",
    country: "España",
    partnerSinceLabel: "Abr 2020",
    rentCommissionPct: 0,
    saleCommissionPct: 0,
    rentCommissionMinPrice: 0,
    saleCommissionMinPrice: 0,
    saleAgreedCommissionPct: 0,
    conditionKeys: [...DEFAULT_CONDITIONS],
    contact: {
      name: "Javier Núñez",
      initials: "JN",
      roleKey: "agency.contact.role.alliancesDirector",
      phone: "+34 91 222 33 44",
      email: "jnunez@gilmar.es",
      address: "Calle de Goya, 21, 28001 Madrid, España",
    },
    properties: [],
  }),
};

export function getAgencyDetail(id: string): AgencyDetail | undefined {
  return mockAgencyDetails[id];
}

function extend(
  base: Agency,
  detail: Omit<AgencyDetail, keyof Agency>,
): AgencyDetail {
  return { ...base, ...detail };
}

function makeFallbackProperties(prefix: string): AgencyPropertyRow[] {
  return [
    {
      id: `${prefix.toLowerCase()}-001`,
      title: "Piso en Salamanca",
      reference: `${prefix}-1001`,
      operation: "alquiler",
      zone: "Salamanca",
      bedrooms: 2,
      bathrooms: 2,
      price: 3200,
      squareMeters: 110,
      status: "available",
      lastUpdateMinutes: 15,
    },
    {
      id: `${prefix.toLowerCase()}-002`,
      title: "Ático en Chamberí",
      reference: `${prefix}-1002`,
      operation: "venta",
      zone: "Chamberí",
      bedrooms: 3,
      bathrooms: 2,
      price: 1450000,
      squareMeters: 155,
      status: "available",
      lastUpdateMinutes: 45,
    },
  ];
}
