import type { AdminClient, ClientsStats } from "@/lib/types";

export const mockClientsStats: ClientsStats = {
  totalClients: 468,
  activeToday: 87,
  visitsRequested: 126,
  customFilters: 312,
  priorityFollowUp: 42,
};

export const mockClients: AdminClient[] = [
  {
    id: "c-maria",
    firstName: "María",
    lastName: "Rodríguez",
    email: "maria.rodriguez@gmail.com",
    phone: "+34 620 123 456",
    location: "Madrid, España",
    avatarInitials: "MA",
    profileType: "worker",
    operation: "alquiler",
    stayType: "corta",
    preferredZone: "Salamanca",
    sector: "Madrid",
    budgetMin: 1200,
    budgetMax: 2500,
    lastAccessLabelKey: "inicio.time.todayAt",
    lastAccessValue: "11:32",
    status: "active",
    assignedAdvisor: "Laura Gómez",
    activity: {
      propertiesViewed: 23,
      favorites: 7,
      visitsRequested: 3,
      messages: 5,
      lastConnectionLabelKey: "inicio.time.todayAt",
      lastConnectionValue: "11:32",
    },
    internalNotes: [
      "Busca 2 habitaciones",
      "Entrada desde septiembre",
      "Cliente interesado en pisos para trabajador desplazado",
    ],
    priority: "high",
  },
  {
    id: "c-javier",
    firstName: "Javier",
    lastName: "Blanco",
    email: "javier.blanco@outlook.es",
    phone: "+34 600 234 567",
    location: "Madrid, España",
    avatarInitials: "JB",
    profileType: "worker",
    operation: "venta",
    stayType: "larga",
    preferredZone: "Chamberí",
    sector: "Madrid",
    budgetMin: 250000,
    budgetMax: 600000,
    lastAccessLabelKey: "inicio.time.yesterdayAt",
    lastAccessValue: "18:45",
    status: "active",
    assignedAdvisor: "Carlos Ruiz",
    activity: {
      propertiesViewed: 11,
      favorites: 3,
      visitsRequested: 1,
      messages: 2,
      lastConnectionLabelKey: "inicio.time.yesterdayAt",
      lastConnectionValue: "18:45",
    },
    internalNotes: [],
    priority: "normal",
  },
  {
    id: "c-clara",
    firstName: "Clara",
    lastName: "Pérez",
    email: "clara.perez@gmail.com",
    phone: "+34 611 345 678",
    location: "Madrid, España",
    avatarInitials: "CP",
    profileType: "student",
    operation: "alquiler",
    stayType: "corta",
    preferredZone: "Centro",
    sector: "Madrid",
    budgetMin: 600,
    budgetMax: 1100,
    lastAccessLabelKey: "inicio.time.yesterdayAt",
    lastAccessValue: "16:20",
    status: "active",
    assignedAdvisor: "Laura Gómez",
    activity: {
      propertiesViewed: 18,
      favorites: 4,
      visitsRequested: 2,
      messages: 1,
      lastConnectionLabelKey: "inicio.time.yesterdayAt",
      lastConnectionValue: "16:20",
    },
    internalNotes: ["Curso académico septiembre-junio"],
    priority: "normal",
  },
  {
    id: "c-luis",
    firstName: "Luis",
    lastName: "Martínez",
    email: "luis.martinez@hotmail.com",
    phone: "+34 622 456 789",
    location: "Madrid, España",
    avatarInitials: "LM",
    profileType: "worker",
    operation: "alquiler",
    stayType: "larga",
    preferredZone: "Chamartín",
    sector: "Madrid",
    budgetMin: 1500,
    budgetMax: 2800,
    lastAccessText: "15/05/2024",
    status: "active",
    assignedAdvisor: "Marta López",
    activity: {
      propertiesViewed: 6,
      favorites: 2,
      visitsRequested: 0,
      messages: 0,
      lastConnectionText: "15/05/2024",
    },
    internalNotes: [],
    priority: "normal",
  },
  {
    id: "c-sofia",
    firstName: "Sofía",
    lastName: "Ramírez",
    email: "sofia.ramirez@gmail.com",
    phone: "+34 633 567 890",
    location: "Madrid, España",
    avatarInitials: "SR",
    profileType: "student",
    operation: "alquiler",
    stayType: "corta",
    preferredZone: "Salamanca",
    sector: "Madrid",
    budgetMin: 700,
    budgetMax: 1200,
    lastAccessText: "14/05/2024",
    status: "inactive",
    assignedAdvisor: "Carlos Ruiz",
    activity: {
      propertiesViewed: 4,
      favorites: 1,
      visitsRequested: 0,
      messages: 0,
      lastConnectionText: "14/05/2024",
    },
    internalNotes: [],
    priority: "normal",
  },
  {
    id: "c-tech",
    firstName: "Tech Solutions",
    lastName: "S.L.",
    email: "contacto@techsolutions.es",
    phone: "+34 910 678 901",
    location: "Madrid, España",
    avatarInitials: "TS",
    profileType: "company",
    operation: "alquiler",
    stayType: "larga",
    preferredZone: "Madrid",
    sector: "Madrid",
    budgetMin: 3000,
    budgetMax: 6000,
    lastAccessText: "14/05/2024",
    status: "active",
    assignedAdvisor: "Marta López",
    activity: {
      propertiesViewed: 15,
      favorites: 5,
      visitsRequested: 4,
      messages: 3,
      lastConnectionText: "14/05/2024",
    },
    internalNotes: [
      "Búsqueda corporativa para 4 empleados desplazados",
      "Necesitan facturación con CIF",
    ],
    priority: "high",
  },
  {
    id: "c-ana",
    firstName: "Ana",
    lastName: "Vázquez",
    email: "ana.vazquez@gmail.com",
    phone: "+34 644 789 012",
    location: "Madrid, España",
    avatarInitials: "AV",
    profileType: "worker",
    operation: "venta",
    stayType: "larga",
    preferredZone: "Retiro",
    sector: "Madrid",
    budgetMin: 350000,
    budgetMax: 800000,
    lastAccessText: "13/05/2024",
    status: "active",
    assignedAdvisor: "Laura Gómez",
    activity: {
      propertiesViewed: 9,
      favorites: 2,
      visitsRequested: 1,
      messages: 1,
      lastConnectionText: "13/05/2024",
    },
    internalNotes: [],
    priority: "normal",
  },
  {
    id: "c-diego",
    firstName: "Diego",
    lastName: "Palacios",
    email: "diego.palacios@icloud.com",
    phone: "+34 655 890 123",
    location: "Madrid, España",
    avatarInitials: "DP",
    profileType: "worker",
    operation: "alquiler",
    stayType: "corta",
    preferredZone: "Tetuán",
    sector: "Madrid",
    budgetMin: 900,
    budgetMax: 1500,
    lastAccessText: "12/05/2024",
    status: "inactive",
    assignedAdvisor: "Carlos Ruiz",
    activity: {
      propertiesViewed: 2,
      favorites: 0,
      visitsRequested: 0,
      messages: 0,
      lastConnectionText: "12/05/2024",
    },
    internalNotes: [],
    priority: "normal",
  },
];

export function getClientById(id: string): AdminClient | undefined {
  return mockClients.find((c) => c.id === id);
}
