/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as OffMarketRouteImport } from './routes/off-market'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades.$id'

const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const OffMarketRoute = OffMarketRouteImport.update({
  id: '/off-market',
  path: '/off-market',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropiedadesRoute,
} as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropiedadesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/off-market': typeof OffMarketRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/off-market': typeof OffMarketRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades': typeof PropiedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/off-market': typeof OffMarketRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/off-market'
    | '/propiedades'
    | '/propiedades/$id'
    | '/propiedades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/off-market'
    | '/propiedades/$id'
    | '/propiedades'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/off-market'
    | '/propiedades'
    | '/propiedades/$id'
    | '/propiedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  OffMarketRoute: typeof OffMarketRoute
  PropiedadesRoute: typeof PropiedadesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-market': {
      id: '/off-market'
      path: '/off-market'
      fullPath: '/off-market'
      preLoaderRoute: typeof OffMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof PropiedadesRoute
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof PropiedadesRoute
    }
  }
}

interface PropiedadesRouteChildren {
  PropiedadesIdRoute: typeof PropiedadesIdRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

const PropiedadesRouteChildren: PropiedadesRouteChildren = {
  PropiedadesIdRoute: PropiedadesIdRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}

const PropiedadesRouteWithChildren = PropiedadesRoute._addFileChildren(
  PropiedadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  OffMarketRoute: OffMarketRoute,
  PropiedadesRoute: PropiedadesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
