-- ============================================================================
-- SmartBC · Reparación del maestro geográfico de Chile
-- ============================================================================
-- La migración 0049_chile_master_data.sql creó las tablas chile_regions /
-- chile_communes / chile_zones pero su seed NUNCA llegó a ejecutarse: tiene dos
-- comillas simples sin escapar que rompen el SQL,
--
--     ('VI', 'O'Higgins', 'Región del Libertador General Bernardo O'Higgins'),
--                 ^                                                  ^
--     ('Centro'), ('Estación Central'), ('Parque O'Higgins'),
--
-- En PostgreSQL eso es un error de sintaxis que aborta la sentencia entera, y
-- con ON_ERROR_STOP=1 aborta el resto del fichero. Resultado: las tres tablas
-- quedaron VACÍAS en producción desde entonces, sin que nada lo delatara.
--
-- Lo destapó la API pública: GET /api/v1/catalogos?tipo=regiones devolvía [],
-- así que un integrador externo no tenía contra qué normalizar región y comuna
-- —justo lo que la documentación le pide hacer— y acababa mandando la
-- nomenclatura de su propia base de datos.
--
-- Esta migración reescribe el seed correctamente escapado y COMPLETO: las 16
-- regiones y las 346 comunas oficiales de Chile (antes solo se intentaban ~40).
-- Es idempotente (ON CONFLICT DO NOTHING), así que se puede reejecutar.
--
-- No se toca 0049: reescribir una migración ya registrada en schema_migrations
-- no se volvería a aplicar en los VPS que la tienen marcada, y sí se aplicaría
-- dos veces en los que usan post-deploy.sh. Se corrige hacia delante.
-- ============================================================================

-- Las tablas pueden no existir si 0049 abortó antes de crearlas.
CREATE TABLE IF NOT EXISTS chile_regions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  full_name TEXT
);

CREATE TABLE IF NOT EXISTS chile_communes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  region_id UUID NOT NULL REFERENCES chile_regions(id),
  code TEXT UNIQUE,
  name TEXT NOT NULL,
  UNIQUE(region_id, name)
);

CREATE TABLE IF NOT EXISTS chile_zones (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  commune_id UUID NOT NULL REFERENCES chile_communes(id),
  name TEXT NOT NULL,
  UNIQUE(commune_id, name)
);

CREATE INDEX IF NOT EXISTS idx_chile_communes_region_id ON chile_communes(region_id);
CREATE INDEX IF NOT EXISTS idx_chile_zones_commune_id ON chile_zones(commune_id);

-- 0049 asignaba a Los Ríos el código XVI, que en realidad es el de Ñuble. Si
-- alguna instalación llegó a insertarlo, se corrige antes de sembrar Ñuble para
-- que no choque contra el UNIQUE de `code`.
UPDATE chile_regions
   SET code = 'XIV', full_name = 'Región de Los Ríos'
 WHERE name = 'Los Ríos' AND code = 'XVI';

-- Regiones (16)
INSERT INTO chile_regions (code, name, full_name) VALUES
  ('XV', 'Arica y Parinacota', 'Región de Arica y Parinacota'),
  ('I', 'Tarapacá', 'Región de Tarapacá'),
  ('II', 'Antofagasta', 'Región de Antofagasta'),
  ('III', 'Atacama', 'Región de Atacama'),
  ('IV', 'Coquimbo', 'Región de Coquimbo'),
  ('V', 'Valparaíso', 'Región de Valparaíso'),
  ('RM', 'Metropolitana', 'Región Metropolitana de Santiago'),
  ('VI', 'O''Higgins', 'Región del Libertador General Bernardo O''Higgins'),
  ('VII', 'Maule', 'Región del Maule'),
  ('XVI', 'Ñuble', 'Región de Ñuble'),
  ('VIII', 'Biobío', 'Región del Biobío'),
  ('IX', 'La Araucanía', 'Región de La Araucanía'),
  ('XIV', 'Los Ríos', 'Región de Los Ríos'),
  ('X', 'Los Lagos', 'Región de Los Lagos'),
  ('XI', 'Aysén', 'Región de Aysén del General Carlos Ibáñez del Campo'),
  ('XII', 'Magallanes', 'Región de Magallanes y de la Antártica Chilena')
ON CONFLICT (code) DO NOTHING;

-- Comunas (346, listado completo oficial)
INSERT INTO chile_communes (region_id, name)
SELECT cr.id, data.commune
FROM (VALUES
  ('XV', 'Arica'),
  ('XV', 'Camarones'),
  ('XV', 'Putre'),
  ('XV', 'General Lagos'),
  ('I', 'Iquique'),
  ('I', 'Alto Hospicio'),
  ('I', 'Pozo Almonte'),
  ('I', 'Camiña'),
  ('I', 'Colchane'),
  ('I', 'Huara'),
  ('I', 'Pica'),
  ('II', 'Antofagasta'),
  ('II', 'Mejillones'),
  ('II', 'Sierra Gorda'),
  ('II', 'Taltal'),
  ('II', 'Calama'),
  ('II', 'Ollagüe'),
  ('II', 'San Pedro de Atacama'),
  ('II', 'Tocopilla'),
  ('II', 'María Elena'),
  ('III', 'Copiapó'),
  ('III', 'Caldera'),
  ('III', 'Tierra Amarilla'),
  ('III', 'Chañaral'),
  ('III', 'Diego de Almagro'),
  ('III', 'Vallenar'),
  ('III', 'Alto del Carmen'),
  ('III', 'Freirina'),
  ('III', 'Huasco'),
  ('IV', 'La Serena'),
  ('IV', 'Coquimbo'),
  ('IV', 'Andacollo'),
  ('IV', 'La Higuera'),
  ('IV', 'Paihuano'),
  ('IV', 'Vicuña'),
  ('IV', 'Illapel'),
  ('IV', 'Canela'),
  ('IV', 'Los Vilos'),
  ('IV', 'Salamanca'),
  ('IV', 'Ovalle'),
  ('IV', 'Combarbalá'),
  ('IV', 'Monte Patria'),
  ('IV', 'Punitaqui'),
  ('IV', 'Río Hurtado'),
  ('V', 'Valparaíso'),
  ('V', 'Casablanca'),
  ('V', 'Concón'),
  ('V', 'Juan Fernández'),
  ('V', 'Puchuncaví'),
  ('V', 'Quintero'),
  ('V', 'Viña del Mar'),
  ('V', 'Isla de Pascua'),
  ('V', 'Los Andes'),
  ('V', 'Calle Larga'),
  ('V', 'Rinconada'),
  ('V', 'San Esteban'),
  ('V', 'La Ligua'),
  ('V', 'Cabildo'),
  ('V', 'Papudo'),
  ('V', 'Petorca'),
  ('V', 'Zapallar'),
  ('V', 'Quillota'),
  ('V', 'La Calera'),
  ('V', 'Hijuelas'),
  ('V', 'La Cruz'),
  ('V', 'Nogales'),
  ('V', 'San Antonio'),
  ('V', 'Algarrobo'),
  ('V', 'Cartagena'),
  ('V', 'El Quisco'),
  ('V', 'El Tabo'),
  ('V', 'Santo Domingo'),
  ('V', 'San Felipe'),
  ('V', 'Catemu'),
  ('V', 'Llaillay'),
  ('V', 'Panquehue'),
  ('V', 'Putaendo'),
  ('V', 'Santa María'),
  ('V', 'Quilpué'),
  ('V', 'Limache'),
  ('V', 'Olmué'),
  ('V', 'Villa Alemana'),
  ('RM', 'Santiago'),
  ('RM', 'Cerrillos'),
  ('RM', 'Cerro Navia'),
  ('RM', 'Conchalí'),
  ('RM', 'El Bosque'),
  ('RM', 'Estación Central'),
  ('RM', 'Huechuraba'),
  ('RM', 'Independencia'),
  ('RM', 'La Cisterna'),
  ('RM', 'La Florida'),
  ('RM', 'La Granja'),
  ('RM', 'La Pintana'),
  ('RM', 'La Reina'),
  ('RM', 'Las Condes'),
  ('RM', 'Lo Barnechea'),
  ('RM', 'Lo Espejo'),
  ('RM', 'Lo Prado'),
  ('RM', 'Macul'),
  ('RM', 'Maipú'),
  ('RM', 'Ñuñoa'),
  ('RM', 'Pedro Aguirre Cerda'),
  ('RM', 'Peñalolén'),
  ('RM', 'Providencia'),
  ('RM', 'Pudahuel'),
  ('RM', 'Quilicura'),
  ('RM', 'Quinta Normal'),
  ('RM', 'Recoleta'),
  ('RM', 'Renca'),
  ('RM', 'San Joaquín'),
  ('RM', 'San Miguel'),
  ('RM', 'San Ramón'),
  ('RM', 'Vitacura'),
  ('RM', 'Puente Alto'),
  ('RM', 'Pirque'),
  ('RM', 'San José de Maipo'),
  ('RM', 'Colina'),
  ('RM', 'Lampa'),
  ('RM', 'Tiltil'),
  ('RM', 'San Bernardo'),
  ('RM', 'Buin'),
  ('RM', 'Calera de Tango'),
  ('RM', 'Paine'),
  ('RM', 'Melipilla'),
  ('RM', 'Alhué'),
  ('RM', 'Curacaví'),
  ('RM', 'María Pinto'),
  ('RM', 'San Pedro'),
  ('RM', 'Talagante'),
  ('RM', 'El Monte'),
  ('RM', 'Isla de Maipo'),
  ('RM', 'Padre Hurtado'),
  ('RM', 'Peñaflor'),
  ('VI', 'Rancagua'),
  ('VI', 'Codegua'),
  ('VI', 'Coinco'),
  ('VI', 'Coltauco'),
  ('VI', 'Doñihue'),
  ('VI', 'Graneros'),
  ('VI', 'Las Cabras'),
  ('VI', 'Machalí'),
  ('VI', 'Malloa'),
  ('VI', 'Mostazal'),
  ('VI', 'Olivar'),
  ('VI', 'Peumo'),
  ('VI', 'Pichidegua'),
  ('VI', 'Quinta de Tilcoco'),
  ('VI', 'Rengo'),
  ('VI', 'Requínoa'),
  ('VI', 'San Vicente'),
  ('VI', 'Pichilemu'),
  ('VI', 'La Estrella'),
  ('VI', 'Litueche'),
  ('VI', 'Marchihue'),
  ('VI', 'Navidad'),
  ('VI', 'Paredones'),
  ('VI', 'San Fernando'),
  ('VI', 'Chépica'),
  ('VI', 'Chimbarongo'),
  ('VI', 'Lolol'),
  ('VI', 'Nancagua'),
  ('VI', 'Palmilla'),
  ('VI', 'Peralillo'),
  ('VI', 'Placilla'),
  ('VI', 'Pumanque'),
  ('VI', 'Santa Cruz'),
  ('VII', 'Talca'),
  ('VII', 'Constitución'),
  ('VII', 'Curepto'),
  ('VII', 'Empedrado'),
  ('VII', 'Maule'),
  ('VII', 'Pelarco'),
  ('VII', 'Pencahue'),
  ('VII', 'Río Claro'),
  ('VII', 'San Clemente'),
  ('VII', 'San Rafael'),
  ('VII', 'Cauquenes'),
  ('VII', 'Chanco'),
  ('VII', 'Pelluhue'),
  ('VII', 'Curicó'),
  ('VII', 'Hualañé'),
  ('VII', 'Licantén'),
  ('VII', 'Molina'),
  ('VII', 'Rauco'),
  ('VII', 'Romeral'),
  ('VII', 'Sagrada Familia'),
  ('VII', 'Teno'),
  ('VII', 'Vichuquén'),
  ('VII', 'Linares'),
  ('VII', 'Colbún'),
  ('VII', 'Longaví'),
  ('VII', 'Parral'),
  ('VII', 'Retiro'),
  ('VII', 'San Javier'),
  ('VII', 'Villa Alegre'),
  ('VII', 'Yerbas Buenas'),
  ('XVI', 'Chillán'),
  ('XVI', 'Bulnes'),
  ('XVI', 'Chillán Viejo'),
  ('XVI', 'El Carmen'),
  ('XVI', 'Pemuco'),
  ('XVI', 'Pinto'),
  ('XVI', 'Quillón'),
  ('XVI', 'San Ignacio'),
  ('XVI', 'Yungay'),
  ('XVI', 'Quirihue'),
  ('XVI', 'Cobquecura'),
  ('XVI', 'Coelemu'),
  ('XVI', 'Ninhue'),
  ('XVI', 'Portezuelo'),
  ('XVI', 'Ránquil'),
  ('XVI', 'Treguaco'),
  ('XVI', 'San Carlos'),
  ('XVI', 'Coihueco'),
  ('XVI', 'Ñiquén'),
  ('XVI', 'San Fabián'),
  ('XVI', 'San Nicolás'),
  ('VIII', 'Concepción'),
  ('VIII', 'Coronel'),
  ('VIII', 'Chiguayante'),
  ('VIII', 'Florida'),
  ('VIII', 'Hualqui'),
  ('VIII', 'Lota'),
  ('VIII', 'Penco'),
  ('VIII', 'San Pedro de la Paz'),
  ('VIII', 'Santa Juana'),
  ('VIII', 'Talcahuano'),
  ('VIII', 'Tomé'),
  ('VIII', 'Hualpén'),
  ('VIII', 'Lebu'),
  ('VIII', 'Arauco'),
  ('VIII', 'Cañete'),
  ('VIII', 'Contulmo'),
  ('VIII', 'Curanilahue'),
  ('VIII', 'Los Álamos'),
  ('VIII', 'Tirúa'),
  ('VIII', 'Los Ángeles'),
  ('VIII', 'Antuco'),
  ('VIII', 'Cabrero'),
  ('VIII', 'Laja'),
  ('VIII', 'Mulchén'),
  ('VIII', 'Nacimiento'),
  ('VIII', 'Negrete'),
  ('VIII', 'Quilaco'),
  ('VIII', 'Quilleco'),
  ('VIII', 'San Rosendo'),
  ('VIII', 'Santa Bárbara'),
  ('VIII', 'Tucapel'),
  ('VIII', 'Yumbel'),
  ('VIII', 'Alto Biobío'),
  ('IX', 'Temuco'),
  ('IX', 'Carahue'),
  ('IX', 'Cunco'),
  ('IX', 'Curarrehue'),
  ('IX', 'Freire'),
  ('IX', 'Galvarino'),
  ('IX', 'Gorbea'),
  ('IX', 'Lautaro'),
  ('IX', 'Loncoche'),
  ('IX', 'Melipeuco'),
  ('IX', 'Nueva Imperial'),
  ('IX', 'Padre Las Casas'),
  ('IX', 'Perquenco'),
  ('IX', 'Pitrufquén'),
  ('IX', 'Pucón'),
  ('IX', 'Saavedra'),
  ('IX', 'Teodoro Schmidt'),
  ('IX', 'Toltén'),
  ('IX', 'Vilcún'),
  ('IX', 'Villarrica'),
  ('IX', 'Cholchol'),
  ('IX', 'Angol'),
  ('IX', 'Collipulli'),
  ('IX', 'Curacautín'),
  ('IX', 'Ercilla'),
  ('IX', 'Lonquimay'),
  ('IX', 'Los Sauces'),
  ('IX', 'Lumaco'),
  ('IX', 'Purén'),
  ('IX', 'Renaico'),
  ('IX', 'Traiguén'),
  ('IX', 'Victoria'),
  ('XIV', 'Valdivia'),
  ('XIV', 'Corral'),
  ('XIV', 'Lanco'),
  ('XIV', 'Los Lagos'),
  ('XIV', 'Máfil'),
  ('XIV', 'Mariquina'),
  ('XIV', 'Paillaco'),
  ('XIV', 'Panguipulli'),
  ('XIV', 'La Unión'),
  ('XIV', 'Futrono'),
  ('XIV', 'Lago Ranco'),
  ('XIV', 'Río Bueno'),
  ('X', 'Puerto Montt'),
  ('X', 'Calbuco'),
  ('X', 'Cochamó'),
  ('X', 'Fresia'),
  ('X', 'Frutillar'),
  ('X', 'Los Muermos'),
  ('X', 'Llanquihue'),
  ('X', 'Maullín'),
  ('X', 'Puerto Varas'),
  ('X', 'Castro'),
  ('X', 'Ancud'),
  ('X', 'Chonchi'),
  ('X', 'Curaco de Vélez'),
  ('X', 'Dalcahue'),
  ('X', 'Puqueldón'),
  ('X', 'Queilén'),
  ('X', 'Quellón'),
  ('X', 'Quemchi'),
  ('X', 'Quinchao'),
  ('X', 'Osorno'),
  ('X', 'Puerto Octay'),
  ('X', 'Purranque'),
  ('X', 'Puyehue'),
  ('X', 'Río Negro'),
  ('X', 'San Juan de la Costa'),
  ('X', 'San Pablo'),
  ('X', 'Chaitén'),
  ('X', 'Futaleufú'),
  ('X', 'Hualaihué'),
  ('X', 'Palena'),
  ('XI', 'Coyhaique'),
  ('XI', 'Lago Verde'),
  ('XI', 'Aysén'),
  ('XI', 'Cisnes'),
  ('XI', 'Guaitecas'),
  ('XI', 'Cochrane'),
  ('XI', 'O''Higgins'),
  ('XI', 'Tortel'),
  ('XI', 'Chile Chico'),
  ('XI', 'Río Ibáñez'),
  ('XII', 'Punta Arenas'),
  ('XII', 'Laguna Blanca'),
  ('XII', 'Río Verde'),
  ('XII', 'San Gregorio'),
  ('XII', 'Cabo de Hornos'),
  ('XII', 'Antártica'),
  ('XII', 'Porvenir'),
  ('XII', 'Primavera'),
  ('XII', 'Timaukel'),
  ('XII', 'Natales'),
  ('XII', 'Torres del Paine')
) AS data(region_code, commune)
JOIN chile_regions cr ON cr.code = data.region_code
ON CONFLICT (region_id, name) DO NOTHING;

-- Sectores de las comunas donde opera la agencia. No pretende ser exhaustivo
-- (los barrios no son una división administrativa); es el conjunto que el
-- equipo usa a diario y se amplía a medida que haga falta.
INSERT INTO chile_zones (commune_id, name)
SELECT cc.id, data.zone
FROM (VALUES
  ('Santiago', 'Centro'),
  ('Santiago', 'Yungay'),
  ('Santiago', 'República'),
  ('Santiago', 'Lastarria'),
  ('Santiago', 'Brasil'),
  ('Santiago', 'Bellas Artes'),
  ('Santiago', 'Barrio Cívico'),
  ('Santiago', 'Parque O''Higgins'),
  ('Las Condes', 'El Golf'),
  ('Las Condes', 'Nueva Las Condes'),
  ('Las Condes', 'Estoril'),
  ('Las Condes', 'San Damián'),
  ('Las Condes', 'Los Dominicos'),
  ('Las Condes', 'Apoquindo'),
  ('Las Condes', 'Cantagallo'),
  ('Vitacura', 'Santa María de Manquehue'),
  ('Vitacura', 'Jardín del Este'),
  ('Vitacura', 'Lo Curro'),
  ('Providencia', 'Barrio Italia'),
  ('Providencia', 'Pedro de Valdivia'),
  ('Providencia', 'Los Leones'),
  ('Providencia', 'Manuel Montt'),
  ('Lo Barnechea', 'La Dehesa'),
  ('Lo Barnechea', 'Los Trapenses'),
  ('Lo Barnechea', 'El Arrayán'),
  ('Lo Barnechea', 'Valle Escondido'),
  ('Ñuñoa', 'Plaza Ñuñoa'),
  ('Ñuñoa', 'Villa Frei'),
  ('Ñuñoa', 'Estadio Nacional'),
  ('La Reina', 'Plaza Egaña'),
  ('Huechuraba', 'Ciudad Empresarial')
) AS data(commune, zone)
JOIN chile_communes cc ON cc.name = data.commune
JOIN chile_regions cr ON cr.id = cc.region_id AND cr.code = 'RM'
ON CONFLICT (commune_id, name) DO NOTHING;

-- Fuerza a PostgREST a recargar la caché de esquema.
NOTIFY pgrst, 'reload schema';
